### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by wingedonezero** [coraxx/MergeSynced#1]
Been looking for something of this sort for a while. Any chance of a linux version? Tried via wine but it wouldn't work.

**Comment by coraxx** [comment]
I was already thinking about porting it to .Net standard with a cross platform UI like avalonia or something like that. I cannot promise anything though 😄

**Comment by coraxx** [comment]
Give pre release version [2.0.0 ](https://github.com/coraxx/MergeSynced/releases/tag/v2.0.0) a try. Can't promise anything though, sry. I currently have not that much time to test it thoroughly.

**Comment by wingedonezero** [comment]
> 

Ill give it test tonight and tomorrow and report back. Thank you for the update. Ill do some testing when i get home.

**Comment by coraxx** [comment]
I just realized, I forgot to chmod +x the executable -.-
So you'll probably will have to do it yourself, e.g. `chmod +x ~/Downloads/MergeSynced/MergeSynced`
For the final release I will fix it, hope for your testing you can manage.

**Comment by wingedonezero** [comment]
> I just realized, I forgot to chmod +x the executable -.- So you'll probably will have to do it yourself, e.g. `chmod +x ~/Downloads/MergeSynced/MergeSynced` For the final release I will fix it, hope for your testing you can manage.

Yea i realized something was off lol. But i think the file naming after exaction has a issue to because ive extracted multiple times and its causing issues still cant run.

![Screenshot_20230413_230611](https://user-images.githubusercontent.com/15163316/231931364-256254aa-2072-4f67-a5ef-a598510a515c.png)

**Comment by coraxx** [comment]
Hi, so i reuploaded a newly packed linux version and tested it in a Ubuntu 22.04 VM. Can you give it another try? :)

**Comment by wingedonezero** [comment]
> Hi, so I reuploaded a newly packed Linux version and tested it in a Ubuntu 22.04 VM. Can you give it another try? :)
> 
> PS: See new pre-release [v2.0.1](https://github.com/coraxx/MergeSynced/releases/tag/v2.0.1)

I was able to download and it opened without issue this time. I'm gonna start testing for issues now i haven't done anything yet but verify it ran. Ill reply back after a bit of testing. I am on debian 11 myself. Thank you for your work so far in this.

**Comment by wingedonezero** [comment]
Ok after some testing most everything works. Although a few issues though. 

Some codecs like thd and such do not decode to work. Wav and ac3 work along with some others. But in other applications those file do work for me using ffmpeg. It does look like it is using the system version of ffmpeg. So im not quite sure what would cause that issue where some codecs work and others do not. I do have 4.4.4 installed and it does support the codecs im trying to use in other apps as noted above. I get error probing with the ones that do not work. But when i check-mark the box for use mkvmerge it does see the audio type then does nothing.

I will say the delay feature does seem accurate as im testing vs some files i manually matched and noted previously. It does even work for files where language is different so long as the sounds and music are all the same. Which is one of my goals to use the app. Although it would be useful to allow if you use two containers and they have multiple audios to allow it to detect and correct all of the audios if that makes sense. because some arent the same even if they are in the same container. And the first selected one should always be whats compared against. like a base to compared to all others or something like that. Also as question if i select multiple audios to be merged does it use the delay value on all them?

Few things though now i can make more issues if you want for features and additions.

Edit to above now if i load containers and not just audio. The thd and stuff does work. But it doesn't allow me to full sync everything because. It only allows to sync to one value. Would it be possible to add the ability to have everything sync to the main selected file which would be source 1? And could you allow for a delay to be set for the subtitles as well? Mkvtoolnix does allow this for audios and subs alike. Generally if there are subs on file its synced to the one file already so the delay for the audio would match for the accompanied subs. Maybe this is getting outside of what you are trying to do with the apps would love some feedback though.

But so far what im seeing though this is exactly what im looking for and makes things so much easier for different sync tasks. Removes a lot of manual work with a few more tweaks and additions it'll do everything i was hoping for. Thank you for being responsive i really appreciate it and look forward to your responses on this.

**Comment by coraxx** [comment]
Glad it an be some use for you! And thank you for taking the time to test it.

So here is what it is currently doing: The delay is determined for the selected audio tracks and the set time, default first 20s. When merging, the delay is applied to everything you selected under File B, even subtitles should get the offset. So File A is not touched at all regarding sync offsets.

If there are already desynced streams inside the file, did you try to put the same file in A and B and deselect the desynced audio in A and select it in B and merge them with the correct offset to a new file? I know an auto batch workflow would be nice, but I will probably have not time currently to make that happen, sorry ^^

The cross correlation score will go down the more two audio streams differ, though the delay can still be on point. This is where you have to get a feeling of if this is correct, or maybe play with the sample start time and/or length.

Regarding different ffmpeg versions: If you have multiple versions installed, the one you want to use should be somewhere first in your $PATH. I kept it simple, but maybe the app needs options for a manual path input for the external tools.

The tracks for what I wrote this app initially were simple mp4 camera containers with stereo wav, so ffmpeg just worked. I have to look into more advanced audio streams and if they need special ffmpeg commandline options. But for everything mkv you must use mkvtoolnix.

**Comment by wingedonezero** [comment]
> 

Yea after a week of testing i was using the previous version though. Just saw the new version. I've worked with about 70 or 80 different file pairs. Seems like 60 is the most accurate time frame seems spot on. Using mkvs i have no issue with it doing any type of audio. It was only when trying to do the audios not in a container other than its default. So basically extracted audio.

Now one bug i've found is it will crash at times if you hit abort while its processing actions. Such as merging and ive had a couple while aborting while it was calculating a longer time frame. Everything else seems to work just fine. Only other thing at this time which idk if its on the windows version. But drag and drop support ive tried to do that and it just freezes for a sec then doesn't work. 

Ill prolly have more for you at a later time as i have a lot of use for the app now. And it really does cut my time by prolly 90 percent. Before i would have to use audacity and find offset that way and sometimes its really hard unless there is a high peak that matches. There was another tool i tried using before but sometimes it would be way off. The way you have this is spot on just about everytime. Ive been double checking to make sure i didn't butcher anything while testing. But the correlation your using seems to be working good. Even for the case where languages are different in both files.

**Comment by coraxx** [comment]
I did some improvements of handling external processes. It should be a bit more stable now and if it is crashing, hopefully you will at least give a little bit mir info about the reason (there also should be a log file now in the its temp folder).

Drag and drop works on mac and windows. Ubuntu did not work in my VM. I have to see about that.

Thank you for the praise, I am glad this is some good use to you. And thanks again for all the testing!

**Comment by wingedonezero** [comment]
Closing since support has been added.
