### ISSUE TITLE
Crash when doing longer compares

### ISSUE THREAD

**Issue by wingedonezero** [coraxx/MergeSynced#3]
Now i cannot find a crash log. But what happens is you enter in a value of over 1000 and after a bit of time it crashes. I was having trouble with a sync so i was trying to use a higher value to compare the whole file and after a few minutes it just crashes. I am on debian and dont have issues with smaller values. I've done up to 500 without issues before.

**Comment by coraxx** [comment]
Yeah, the log is only written when a debugger is attached. I already fixed it in a commit on another branch 05f739f1e6c131ef0ce2697d8c0b62dc6bc3459f. I still need to do a few things, then I will do a new release.

Regarding the crash, probably it was using too much RAM. It gets pretty memory intensive with longer pieces of audio. Maybe it is a good idea to add an indicator on how much RAM is still available.

**Comment by wingedonezero** [comment]
> Yeah, the log is only written when a debugger is attached. I already fixed it in a commit on another branch [05f739f](https://github.com/coraxx/MergeSynced/commit/05f739f1e6c131ef0ce2697d8c0b62dc6bc3459f). I still need to do a few things, then I will do a new release.
> 
> Regarding the crash, probably it was using too much RAM. It gets pretty memory intensive with longer pieces of audio. Maybe it is a good idea to add an indicator on how much RAM is still available.

I didnt notice to much ram being used. Ill double check that here tonight. I have 32gbs i feel that should be enough.

**Comment by coraxx** [comment]
So I did one on Windows with 1000s, which is way longer than what I ever planed to use it for ^^ This is like 16 minutes of audio. You normally should not need more like double'ish the delay time of audio.

This consumes roughly 16GB of memory. 

![image](https://user-images.githubusercontent.com/19515548/236340816-9f6d4b1c-e0c4-420a-a4a1-169138990cb9.png)

**Comment by wingedonezero** [comment]
> So I did one on Windows with 1000s, which is way longer than what I ever planed to use it for ^^ This is like 16 minutes of audio. You normally should not need more like double'ish the delay time of audio.
> 
> This consumes roughly 16GB of memory.
> 
> ![image](https://user-images.githubusercontent.com/19515548/236340816-9f6d4b1c-e0c4-420a-a4a1-169138990cb9.png)

Ok then that may explain it. I didn't notice my ram usage being that high when i was trying it. This isnt that big of a deal. I actually thought up an idea to account for that ill open another ticket with that idea when i get a chance here. This was a kinda extreme case where i just couldn't fine tune the delay enough. But the delay does change sometimes depending on the audio being used and the match percentage. So that was my use case. But i have an idea to account for that. Thanks for the response ill close this ticket and open my feature request.
